In [3]:
import pandas as pd
df = pd.read_csv("test.csv")
df

           name  movementSpeed  physicalAttack  armor    hp  mana
0         Layla            270             118     15  2500   424
1       Cyclops            250             107     18  2461   500
2      Minotaur            265             123     25  2705     0
3         Saber            265             121     17  2475   443
4         Roger            235             120     22  2580   450
5          Nana            250             110     17  2325   499
6          Akai            260             115     24  2769   422
7         Alice            240             109     21  2397   493
8         Alpha            236             121     20  2646   453
9       Alucard            265             118     21  2593     0
10        Argus            260             124     21  2628     0
11       Aurora            245             105     17  2441   500
12      Balmond            265             114     23  2602     0
13         Bane            265             117     23  2625   433
14        Bruno            240             116     17  2402   439
15         Chou            265             121     23  2598     0
16        Clint            248             122     20  2500   450
17       Diggie            250             115     16  2351   490
18        Estes            240             115     13  2161   545
19       Eudora            250             112     19  2524   468
20        Fanny            270             126     17  2402     0
21       Franco            255             116     25  2575   440
22        Freya            265             109     22  2673   462
23    Gatotkaca            260             120     20  2709   440
24         Gord            240             105     13  2302   570
25        Grock            260             135     21  2819   430
26       Harley            240             114     19  2501   490
27     Hayabusa            265             114     17  2555   479
28       Helcur            255             121     17  2599   440
29        Hilda            260             123     24  2909     0
30        Hylos            260             105     17  3309   430
31      Irithel            250             110     17  2540   438
32      Johnson            255             112     27  2809     0
33       Kagura            240             113     19  2380   519
34       Karina            265             121     20  2505   431
35       Karrie            240             112     17  2498   440
36     Lancelot            260             124     16  2546   450
37    Lapu-lapu            260             119     21  2628     0
38       Lolita            265             115     27  2545     0
39         Miya            235             114     17  2404   445
40       Moskov            240             125     16  2530   420
41      Natalia            265             121     18  2465   486
42       Odette            240             105     18  2491   495
43       Pharsa            240             109     15  2421   490
44      Rafaela            245             112     15  2265   545
45         Ruby            265             114     23  2709   430
46   Sun Wukong            265             114     23  2630   400
47      Tigreal            265             112     25  2756   450
48       Vexana            245             112     17  2421   490
49  Yi Sun-Shin            240             110     18  2520   438
50     Yun Zhao            270             123     25  2561   405
51        Zhask            240             107     15  2401   490

In [6]:
import csv
with open('test.csv') as csvfile:
    readCSV = csv.reader(csvfile, delimiter=',')
    print(readCSV)

<_csv.reader object at 0x0000005628CE3F50>

In [9]:
import pandas as pd
data = pd.read_csv('test.csv')
print(data)

           name  movementSpeed  physicalAttack  armor    hp  mana
0         Layla            270             118     15  2500   424
1       Cyclops            250             107     18  2461   500
2      Minotaur            265             123     25  2705     0
3         Saber            265             121     17  2475   443
4         Roger            235             120     22  2580   450
5          Nana            250             110     17  2325   499
6          Akai            260             115     24  2769   422
7         Alice            240             109     21  2397   493
8         Alpha            236             121     20  2646   453
9       Alucard            265             118     21  2593     0
10        Argus            260             124     21  2628     0
11       Aurora            245             105     17  2441   500
12      Balmond            265             114     23  2602     0
13         Bane            265             117     23  2625   433
14        Bruno            240             116     17  2402   439
15         Chou            265             121     23  2598     0
16        Clint            248             122     20  2500   450
17       Diggie            250             115     16  2351   490
18        Estes            240             115     13  2161   545
19       Eudora            250             112     19  2524   468
20        Fanny            270             126     17  2402     0
21       Franco            255             116     25  2575   440
22        Freya            265             109     22  2673   462
23    Gatotkaca            260             120     20  2709   440
24         Gord            240             105     13  2302   570
25        Grock            260             135     21  2819   430
26       Harley            240             114     19  2501   490
27     Hayabusa            265             114     17  2555   479
28       Helcur            255             121     17  2599   440
29        Hilda            260             123     24  2909     0
30        Hylos            260             105     17  3309   430
31      Irithel            250             110     17  2540   438
32      Johnson            255             112     27  2809     0
33       Kagura            240             113     19  2380   519
34       Karina            265             121     20  2505   431
35       Karrie            240             112     17  2498   440
36     Lancelot            260             124     16  2546   450
37    Lapu-lapu            260             119     21  2628     0
38       Lolita            265             115     27  2545     0
39         Miya            235             114     17  2404   445
40       Moskov            240             125     16  2530   420
41      Natalia            265             121     18  2465   486
42       Odette            240             105     18  2491   495
43       Pharsa            240             109     15  2421   490
44      Rafaela            245             112     15  2265   545
45         Ruby            265             114     23  2709   430
46   Sun Wukong            265             114     23  2630   400
47      Tigreal            265             112     25  2756   450
48       Vexana            245             112     17  2421   490
49  Yi Sun-Shin            240             110     18  2520   438
50     Yun Zhao            270             123     25  2561   405
51        Zhask            240             107     15  2401   490

In [10]:
import pandas as pd
data = pd.read_csv('test.csv', delimiter="\t")
print(data)

   name,movementSpeed,physicalAttack,armor,hp,mana
0                        Layla,270,118,15,2500,424
1                      Cyclops,250,107,18,2461,500
2                       Minotaur,265,123,25,2705,0
3                        Saber,265,121,17,2475,443
4                        Roger,235,120,22,2580,450
5                         Nana,250,110,17,2325,499
6                         Akai,260,115,24,2769,422
7                        Alice,240,109,21,2397,493
8                        Alpha,236,121,20,2646,453
9                        Alucard,265,118,21,2593,0
10                         Argus,260,124,21,2628,0
11                      Aurora,245,105,17,2441,500
12                       Balmond,265,114,23,2602,0
13                        Bane,265,117,23,2625,433
14                       Bruno,240,116,17,2402,439
15                          Chou,265,121,23,2598,0
16                       Clint,248,122,20,2500,450
17                      Diggie,250,115,16,2351,490
18                       Estes,240,115,13,2161,545
19                      Eudora,250,112,19,2524,468
20                         Fanny,270,126,17,2402,0
21                      Franco,255,116,25,2575,440
22                       Freya,265,109,22,2673,462
23                   Gatotkaca,260,120,20,2709,440
24                        Gord,240,105,13,2302,570
25                       Grock,260,135,21,2819,430
26                      Harley,240,114,19,2501,490
27                    Hayabusa,265,114,17,2555,479
28                      Helcur,255,121,17,2599,440
29                         Hilda,260,123,24,2909,0
30                       Hylos,260,105,17,3309,430
31                     Irithel,250,110,17,2540,438
32                       Johnson,255,112,27,2809,0
33                      Kagura,240,113,19,2380,519
34                      Karina,265,121,20,2505,431
35                      Karrie,240,112,17,2498,440
36                    Lancelot,260,124,16,2546,450
37                     Lapu-lapu,260,119,21,2628,0
38                        Lolita,265,115,27,2545,0
39                        Miya,235,114,17,2404,445
40                      Moskov,240,125,16,2530,420
41                     Natalia,265,121,18,2465,486
42                      Odette,240,105,18,2491,495
43                      Pharsa,240,109,15,2421,490
44                     Rafaela,245,112,15,2265,545
45                        Ruby,265,114,23,2709,430
46                  Sun Wukong,265,114,23,2630,400
47                     Tigreal,265,112,25,2756,450
48                      Vexana,245,112,17,2421,490
49                 Yi Sun-Shin,240,110,18,2520,438
50                    Yun Zhao,270,123,25,2561,405
51                       Zhask,240,107,15,2401,490

In [11]:
import pandas as pd
data = pd.read_csv('test.csv', delimiter=",")
print(data)

           name  movementSpeed  physicalAttack  armor    hp  mana
0         Layla            270             118     15  2500   424
1       Cyclops            250             107     18  2461   500
2      Minotaur            265             123     25  2705     0
3         Saber            265             121     17  2475   443
4         Roger            235             120     22  2580   450
5          Nana            250             110     17  2325   499
6          Akai            260             115     24  2769   422
7         Alice            240             109     21  2397   493
8         Alpha            236             121     20  2646   453
9       Alucard            265             118     21  2593     0
10        Argus            260             124     21  2628     0
11       Aurora            245             105     17  2441   500
12      Balmond            265             114     23  2602     0
13         Bane            265             117     23  2625   433
14        Bruno            240             116     17  2402   439
15         Chou            265             121     23  2598     0
16        Clint            248             122     20  2500   450
17       Diggie            250             115     16  2351   490
18        Estes            240             115     13  2161   545
19       Eudora            250             112     19  2524   468
20        Fanny            270             126     17  2402     0
21       Franco            255             116     25  2575   440
22        Freya            265             109     22  2673   462
23    Gatotkaca            260             120     20  2709   440
24         Gord            240             105     13  2302   570
25        Grock            260             135     21  2819   430
26       Harley            240             114     19  2501   490
27     Hayabusa            265             114     17  2555   479
28       Helcur            255             121     17  2599   440
29        Hilda            260             123     24  2909     0
30        Hylos            260             105     17  3309   430
31      Irithel            250             110     17  2540   438
32      Johnson            255             112     27  2809     0
33       Kagura            240             113     19  2380   519
34       Karina            265             121     20  2505   431
35       Karrie            240             112     17  2498   440
36     Lancelot            260             124     16  2546   450
37    Lapu-lapu            260             119     21  2628     0
38       Lolita            265             115     27  2545     0
39         Miya            235             114     17  2404   445
40       Moskov            240             125     16  2530   420
41      Natalia            265             121     18  2465   486
42       Odette            240             105     18  2491   495
43       Pharsa            240             109     15  2421   490
44      Rafaela            245             112     15  2265   545
45         Ruby            265             114     23  2709   430
46   Sun Wukong            265             114     23  2630   400
47      Tigreal            265             112     25  2756   450
48       Vexana            245             112     17  2421   490
49  Yi Sun-Shin            240             110     18  2520   438
50     Yun Zhao            270             123     25  2561   405
51        Zhask            240             107     15  2401   490

In [12]:
import pandas as pd
df = pd.read_csv('test.csv', sep=" ", header=None, names=["a", "b", "c"])
print(data)

           name  movementSpeed  physicalAttack  armor    hp  mana
0         Layla            270             118     15  2500   424
1       Cyclops            250             107     18  2461   500
2      Minotaur            265             123     25  2705     0
3         Saber            265             121     17  2475   443
4         Roger            235             120     22  2580   450
5          Nana            250             110     17  2325   499
6          Akai            260             115     24  2769   422
7         Alice            240             109     21  2397   493
8         Alpha            236             121     20  2646   453
9       Alucard            265             118     21  2593     0
10        Argus            260             124     21  2628     0
11       Aurora            245             105     17  2441   500
12      Balmond            265             114     23  2602     0
13         Bane            265             117     23  2625   433
14        Bruno            240             116     17  2402   439
15         Chou            265             121     23  2598     0
16        Clint            248             122     20  2500   450
17       Diggie            250             115     16  2351   490
18        Estes            240             115     13  2161   545
19       Eudora            250             112     19  2524   468
20        Fanny            270             126     17  2402     0
21       Franco            255             116     25  2575   440
22        Freya            265             109     22  2673   462
23    Gatotkaca            260             120     20  2709   440
24         Gord            240             105     13  2302   570
25        Grock            260             135     21  2819   430
26       Harley            240             114     19  2501   490
27     Hayabusa            265             114     17  2555   479
28       Helcur            255             121     17  2599   440
29        Hilda            260             123     24  2909     0
30        Hylos            260             105     17  3309   430
31      Irithel            250             110     17  2540   438
32      Johnson            255             112     27  2809     0
33       Kagura            240             113     19  2380   519
34       Karina            265             121     20  2505   431
35       Karrie            240             112     17  2498   440
36     Lancelot            260             124     16  2546   450
37    Lapu-lapu            260             119     21  2628     0
38       Lolita            265             115     27  2545     0
39         Miya            235             114     17  2404   445
40       Moskov            240             125     16  2530   420
41      Natalia            265             121     18  2465   486
42       Odette            240             105     18  2491   495
43       Pharsa            240             109     15  2421   490
44      Rafaela            245             112     15  2265   545
45         Ruby            265             114     23  2709   430
46   Sun Wukong            265             114     23  2630   400
47      Tigreal            265             112     25  2756   450
48       Vexana            245             112     17  2421   490
49  Yi Sun-Shin            240             110     18  2520   438
50     Yun Zhao            270             123     25  2561   405
51        Zhask            240             107     15  2401   490

In [14]:
def loadtest(filename, trainingSet=[]):
    with open(filename, 'cs') as csvfile:
        lines = csv.reader(csvfile)
        dataset = list(lines)
        for x in range(len(dataset)):
            for y in range(4):
                dataset[x][y] = float(dataset[x][y])
            trainingSet.append(dataset[x])

In [17]:
import csv
with open('test.csv') as csvfile:
reader = csv.reader(csvfile, delimiter=",")
for row in readCSV:
print(row)

IndentationError: expected an indented block (<ipython-input-17-64054fa4f15e>, line 3)

In [18]:
import csv
 
file = open('test.csv', 'r')
reader = csv.reader(file)
for data in reader:
    print(data)

['name', 'movementSpeed', 'physicalAttack', 'armor', 'hp', 'mana']
['Layla', '270', '118', '15', '2500', '424']
['Cyclops', '250', '107', '18', '2461', '500']
['Minotaur', '265', '123', '25', '2705', '0']
['Saber', '265', '121', '17', '2475', '443']
['Roger', '235', '120', '22', '2580', '450']
['Nana', '250', '110', '17', '2325', '499']
['Akai', '260', '115', '24', '2769', '422']
['Alice', '240', '109', '21', '2397', '493']
['Alpha', '236', '121', '20', '2646', '453']
['Alucard', '265', '118', '21', '2593', '0']
['Argus', '260', '124', '21', '2628', '0']
['Aurora', '245', '105', '17', '2441', '500']
['Balmond', '265', '114', '23', '2602', '0']
['Bane', '265', '117', '23', '2625', '433']
['Bruno', '240', '116', '17', '2402', '439']
['Chou', '265', '121', '23', '2598', '0']
['Clint', '248', '122', '20', '2500', '450']
['Diggie', '250', '115', '16', '2351', '490']
['Estes', '240', '115', '13', '2161', '545']
['Eudora', '250', '112', '19', '2524', '468']
['Fanny', '270', '126', '17', '2402', '0']
['Franco', '255', '116', '25', '2575', '440']
['Freya', '265', '109', '22', '2673', '462']
['Gatotkaca', '260', '120', '20', '2709', '440']
['Gord', '240', '105', '13', '2302', '570']
['Grock', '260', '135', '21', '2819', '430']
['Harley', '240', '114', '19', '2501', '490']
['Hayabusa', '265', '114', '17', '2555', '479']
['Helcur', '255', '121', '17', '2599', '440']
['Hilda', '260', '123', '24', '2909', '0']
['Hylos', '260', '105', '17', '3309', '430']
['Irithel', '250', '110', '17', '2540', '438']
['Johnson', '255', '112', '27', '2809', '0']
['Kagura', '240', '113', '19', '2380', '519']
['Karina', '265', '121', '20', '2505', '431']
['Karrie', '240', '112', '17', '2498', '440']
['Lancelot', '260', '124', '16', '2546', '450']
['Lapu-lapu', '260', '119', '21', '2628', '0']
['Lolita', '265', '115', '27', '2545', '0']
['Miya', '235', '114', '17', '2404', '445']
['Moskov', '240', '125', '16', '2530', '420']
['Natalia', '265', '121', '18', '2465', '486']
['Odette', '240', '105', '18', '2491', '495']
['Pharsa', '240', '109', '15', '2421', '490']
['Rafaela', '245', '112', '15', '2265', '545']
['Ruby', '265', '114', '23', '2709', '430']
['Sun Wukong', '265', '114', '23', '2630', '400']
['Tigreal', '265', '112', '25', '2756', '450']
['Vexana', '245', '112', '17', '2421', '490']
['Yi Sun-Shin', '240', '110', '18', '2520', '438']
['Yun Zhao', '270', '123', '25', '2561', '405']
['Zhask', '240', '107', '15', '2401', '490']

In [20]:
import csv

import csv

getData = []
saveData = []

saveData.insert(0, ['name', 'role'])

with open('test.csv') as filecsv:
	line = csv.reader(filecsv)
	dataset = list(line)

	for x in range(53):
		for y in range (5):
			dataset[x][y] = dataset[x][y]
		getData.append(dataset[x])
		
for index in range(1, len(getData)):
	if int (getData[index][1]) >= 270:
		saveData.append([getData[index][0], 'MARKSMAN'])
	elif int (getData[index][2]) >= 121:
		saveData.append([getData[index][0], 'ASSASSIN'])
	elif int (getData[index][3]) >= 25:
		saveData.append([getData[index][0], 'TANK'])
	if int (getData[index][4]) >= 2580:
		saveData.append([getData[index][0], 'FIGHTER'])
	if int (getData[index][5]) >= 500:
		saveData.append([getData[index][0], 'MAGE'])
	else: 
		saveData.append([getData[index][0], 'SUPPORT'])
		
with open('Prediction.csv', 'w', newline='') as createcsv:
	new = csv.writer(createcsv)
	for x in range(len(saveData)):
		baris.writerow(saveData[x])

NameError: name 'baris' is not defined

In [21]:
import csv

getData = []
saveData = []

saveData.insert(0, ['name', 'role'])

with open('test.csv') as filecsv:
	line = csv.reader(filecsv)
	dataset = list(line)

	for x in range(53):
		for y in range (5):
			dataset[x][y] = dataset[x][y]
		getData.append(dataset[x])
		
for index in range(1, len(getData)):
	if int (getData[index][1]) >= 270:
		saveData.append([getData[index][0], 'MARKSMAN'])
	elif int (getData[index][2]) >= 121:
		saveData.append([getData[index][0], 'ASSASSIN'])
	elif int (getData[index][3]) >= 25:
		saveData.append([getData[index][0], 'TANK'])
	if int (getData[index][4]) >= 2580:
		saveData.append([getData[index][0], 'FIGHTER'])
	if int (getData[index][5]) >= 500:
		saveData.append([getData[index][0], 'MAGE'])
	else: 
		saveData.append([getData[index][0], 'SUPPORT'])
		
with open('Prediction.csv', 'w', newline='') as createcsv:
	new = csv.writer(createcsv)
	for x in range(len(saveData)):
		new.writerow(saveData[x])

In [22]:
#Laily Dwi Anggaraini
#1301178513
#IF 41 GAB02

import csv #memasukkan file csv

getData = [] #inisialisasi awal variable
saveData = []

saveData.insert(0, ['name', 'role']) #menambahkan baris atau nama kolom

with open('test.csv') as filecsv: 
	line = csv.reader(filecsv)  #membuka file csv yang ada pada disk c 
	dataset = list(line)

	for x in range(53):  #perulangan sejumlah data yang akan dicari 
		for y in range (5):
			dataset[x][y] = dataset[x][y]
		getData.append(dataset[x])
	
for index in range(1, len(getData)): #perulangan untuk mengecek satu persatu hero dan mengambil data
	if int (getData[index][1]) >= 270:
		saveData.append([getData[index][0], 'MARKSMAN'])  #mengecek berdasarkan movementSpeed
	elif int (getData[index][2]) >= 121:
		saveData.append([getData[index][0], 'ASSASSIN'])  #mengecek berdasarkan physicalAttack
	elif int (getData[index][3]) >= 25:
		saveData.append([getData[index][0], 'TANK'])      #mengecek berdasarkan armor
	if int (getData[index][4]) >= 2580:
		saveData.append([getData[index][0], 'FIGHTER'])   #mengecek hp
	if int (getData[index][5]) >= 500:
		saveData.append([getData[index][0], 'MAGE'])      #mengecek mana
	else: 
		saveData.append([getData[index][0], 'SUPPORT'])
		
with open('Prediction.csv', 'w', newline='') as createcsv:   #mengcreate file csv berupa hasil prediksi
	new = csv.writer(createcsv)
	for x in range(len(saveData)):
		new.writerow(saveData[x])

In [23]:
#Laily Dwi Anggaraini
#1301178513
#IF 41 GAB02

import csv #memasukkan file csv

getData = [] #inisialisasi awal variable
saveData = []

saveData.insert(0, ['name', 'role']) #menambahkan baris atau nama kolom

with open('test.csv') as filecsv: 
	line = csv.reader(filecsv)  #membuka file csv yang ada pada disk c 
	dataset = list(line)

	for x in range(53):  #perulangan sejumlah data yang akan dicari 
		for y in range (5):
			dataset[x][y] = dataset[x][y]
		getData.append(dataset[x])
	
for index in range(1, len(getData)): #perulangan untuk mengecek satu persatu hero dan mengambil data
	if int (getData[index][1]) >= 270:
		saveData.append([getData[index][0], 'MARKSMAN'])  #mengecek berdasarkan movementSpeed
	elif int (getData[index][2]) >= 121:
		saveData.append([getData[index][0], 'ASSASSIN'])  #mengecek berdasarkan physicalAttack
	elif int (getData[index][3]) >= 25:
		saveData.append([getData[index][0], 'TANK'])      #mengecek berdasarkan armor
	if int (getData[index][4]) >= 2580:
		saveData.append([getData[index][0], 'FIGHTER'])   #mengecek hp
	if int (getData[index][5]) >= 500:
		saveData.append([getData[index][0], 'MAGE'])      #mengecek mana
	else: 
		saveData.append([getData[index][0], 'SUPPORT'])
		
with open('Prediction1.csv', 'w', newline='') as createcsv:   #mengcreate file csv berupa hasil prediksi
	new = csv.writer(buatcsv)
	for x in range(len(saveData)):
		new.writerow(saveData[x])

NameError: name 'buatcsv' is not defined

In [25]:
#Laily Dwi Anggaraini
#1301178513
#IF 41 GAB02

import csv #memasukkan file csv

getData = [] #inisialisasi awal variable
saveData = []

saveData.insert(0, ['name', 'role']) #menambahkan baris atau nama kolom

with open('test.csv') as filecsv: 
	line = csv.reader(filecsv)  #membuka file csv yang ada pada disk c 
	dataset = list(line)

	for x in range(53):  #perulangan sejumlah data yang akan dicari 
		for y in range (5):
			dataset[x][y] = dataset[x][y]
		getData.append(dataset[x])
	
for index in range(1, len(getData)): #perulangan untuk mengecek satu persatu hero dan mengambil data
	if int (getData[index][1]) >= 270:
		saveData.append([getData[index][0], 'MARKSMAN'])  #mengecek berdasarkan movementSpeed
	elif int (getData[index][2]) >= 121:
		saveData.append([getData[index][0], 'ASSASSIN'])  #mengecek berdasarkan physicalAttack
	elif int (getData[index][3]) >= 25:
		saveData.append([getData[index][0], 'TANK'])      #mengecek berdasarkan armor
	if int (getData[index][4]) >= 2580:
		saveData.append([getData[index][0], 'FIGHTER'])   #mengecek hp
	if int (getData[index][5]) >= 500:
		saveData.append([getData[index][0], 'MAGE'])      #mengecek mana
	else: 
		saveData.append([getData[index][0], 'SUPPORT'])
		
with open('Prediction1.csv', 'w', newline='') as buatcsv:   #mengcreate file csv berupa hasil prediksi
	new = csv.writer(buatcsv)
	for x in range(len(saveData)):
		new.writerow(saveData[x])

In [26]:
#Laily Dwi Anggaraini
#1301178513
#IF 41 GAB02

import csv #memasukkan file csv

getData = [] #inisialisasi awal variable
saveData = []

saveData.insert(0, ['name', 'role']) #menambahkan baris atau nama kolom

with open('test.csv') as filecsv: 
	line = csv.reader(filecsv)  #membuka file csv yang ada pada disk c 
	dataset = list(line)

	for x in range(53):  #perulangan sejumlah data yang akan dicari 
		for y in range (5):
			dataset[x][y] = dataset[x][y]
		getData.append(dataset[x])
	
for index in range(1, len(getData)): #perulangan untuk mengecek satu persatu hero dan mengambil data
	if int (getData[index][1]) >= 270:
		saveData.append([getData[index][0], 'MARKSMAN'])  #mengecek berdasarkan movementSpeed
	elif int (getData[index][2]) >= 121:
		saveData.append([getData[index][0], 'ASSASSIN'])  #mengecek berdasarkan physicalAttack
	elif int (getData[index][3]) >= 25:
		saveData.append([getData[index][0], 'TANK'])      #mengecek berdasarkan armor
	if int (getData[index][4]) >= 2580:
		saveData.append([getData[index][0], 'FIGHTER'])   #mengecek hp
	if int (getData[index][5]) >= 500:
		saveData.append([getData[index][0], 'MAGE'])      #mengecek mana
	else: 
		saveData.append([getData[index][0], 'SUPPORT'])
		
with open('Prediction.csv', 'w', newline='') as buatcsv:   #mengcreate file csv berupa hasil prediksi
	new = csv.writer(buatcsv)
	for x in range(len(saveData)):
		new.writerow(saveData[x])

In [27]:
#buat new pertama/nama kolom
saveData.insert(0, ['name', 'role'])

#buka file test.csv
with open('test.csv') as filecsv:
	line	= csv.reader(filecsv)
	dataset	= list(line)
	#forloop sebanyak 53
	for x in range(53):
		for y in range (5):
			dataset[x][y] = dataset[x][y]
		#tampung ke variable getData
		getData.append(dataset[x])

#forloop untuk getData
for index in range(1, len(getData)):
	#cek movementSpeed
	if int(getData[index][1]) >= 270:
		saveData.append([getData[index][0], 'MARKSMAN'])
	#cek physicalAttack
	elif int(getData[index][2]) >= 121:
		saveData.append([getData[index][0], 'ASSASSIN'])
	#cek armor
	elif int(getData[index][3]) >= 25:
		saveData.append([getData[index][0], 'TANK'])
	#cek hp
	elif int(getData[index][4]) >= 2580:
		saveData.append([getData[index][0], 'FIGHTER'])
	#cek mana
	elif int(getData[index][5]) >= 500:
		saveData.append([getData[index][0], 'MAGE'])
	else:
		saveData.append([getData[index][0], 'SUPPORT'])

#membuat file csv
with open('Prediction.csv', 'w', newline='') as buatcsv:
	new = csv.writer(buatcsv)
	for x in range(len(saveData)):
		new.writerow(saveData[x])

ValueError: invalid literal for int() with base 10: 'movementSpeed'

In [28]:
import csv

#inisialisasi variable
ambilData 	= []
saveData	= []

#buat new pertama/nama kolom
saveData.insert(0, ['name', 'role'])

#buka file test.csv
with open('test.csv') as filecsv:
	line	= csv.reader(filecsv)
	dataset	= list(line)
	#forloop sebanyak 53
	for x in range(53):
		for y in range (5):
			dataset[x][y] = dataset[x][y]
		#tampung ke variable ambilData
		ambilData.append(dataset[x])

#forloop untuk ambilData
for index in range(1, len(ambilData)):
	#cek movementSpeed
	if int(ambilData[index][1]) >= 270:
		saveData.append([ambilData[index][0], 'MARKSMAN'])
	#cek physicalAttack
	elif int(ambilData[index][2]) >= 121:
		saveData.append([ambilData[index][0], 'ASSASSIN'])
	#cek armor
	elif int(ambilData[index][3]) >= 25:
		saveData.append([ambilData[index][0], 'TANK'])
	#cek hp
	elif int(ambilData[index][4]) >= 2580:
		saveData.append([ambilData[index][0], 'FIGHTER'])
	#cek mana
	elif int(ambilData[index][5]) >= 500:
		saveData.append([ambilData[index][0], 'MAGE'])
	else:
		saveData.append([ambilData[index][0], 'SUPPORT'])

#membuat file csv
with open('Prediction.csv', 'w', newline='') as buatcsv:
	new = csv.writer(buatcsv)
	for x in range(len(saveData)):
		new.writerow(saveData[x])

In [29]:
import csv

#inisialisasi variable
getData 	= []
saveData	= []

#buat new pertama/nama kolom
saveData.insert(0, ['name', 'role'])

#buka file test.csv
with open('test.csv') as filecsv:
	line	= csv.reader(filecsv)
	dataset	= list(line)
	#forloop sebanyak 53
	for x in range(53):
		for y in range (5):
			dataset[x][y] = dataset[x][y]
		#tampung ke variable getData
		getData.append(dataset[x])

#forloop untuk getData
for index in range(1, len(getData)):
	#cek movementSpeed
	if int(getData[index][1]) >= 270:
		saveData.append([getData[index][0], 'MARKSMAN'])
	#cek physicalAttack
	elif int(getData[index][2]) >= 121:
		saveData.append([getData[index][0], 'ASSASSIN'])
	#cek armor
	elif int(getData[index][3]) >= 25:
		saveData.append([getData[index][0], 'TANK'])
	#cek hp
	elif int(getData[index][4]) >= 2580:
		saveData.append([getData[index][0], 'FIGHTER'])
	#cek mana
	elif int(getData[index][5]) >= 500:
		saveData.append([getData[index][0], 'MAGE'])
	else:
		saveData.append([getData[index][0], 'SUPPORT'])

#membuat file csv
with open('Prediction.csv', 'w', newline='') as buatcsv:
	new = csv.writer(buatcsv)
	for x in range(len(saveData)):
		new.writerow(saveData[x])

In [30]:
import csv

#inisialisasi variable
takeData 	= []
saveData	= []

#buat new pertama/nama kolom
saveData.insert(0, ['name', 'role'])

#buka file test.csv
with open('test.csv') as filecsv:
	line	= csv.reader(filecsv)
	dataset	= list(line)
	#forloop sebanyak 53
	for x in range(53):
		for y in range (5):
			dataset[x][y] = dataset[x][y]
		#tampung ke variable takeData
		takeData.append(dataset[x])

#forloop untuk takeData
for index in range(1, len(takeData)):
	#cek movementSpeed
	if int(takeData[index][1]) >= 270:
		saveData.append([takeData[index][0], 'MARKSMAN'])
	#cek physicalAttack
	elif int(takeData[index][2]) >= 121:
		saveData.append([takeData[index][0], 'ASSASSIN'])
	#cek armor
	elif int(takeData[index][3]) >= 25:
		saveData.append([takeData[index][0], 'TANK'])
	#cek hp
	elif int(takeData[index][4]) >= 2580:
		saveData.append([takeData[index][0], 'FIGHTER'])
	#cek mana
	elif int(takeData[index][5]) >= 500:
		saveData.append([takeData[index][0], 'MAGE'])
	else:
		saveData.append([takeData[index][0], 'SUPPORT'])

#membuat file csv
with open('Prediction.csv', 'w', newline='') as buatcsv:
	new = csv.writer(buatcsv)
	for x in range(len(saveData)):
		new.writerow(saveData[x])